Repository future4code/mello-labook11, pull requests merged in 2020-08, with the labels that each got.

#1 Configuração inicial do projeto
  .gitignore
  package-lock.json
  package.json
  src/business/UserBusiness.ts
  src/data/BaseDatabase.ts
  src/data/UserDatabase.ts
  src/index.ts
  src/services/Authenticator.ts
  src/services/HashManager.ts
  src/services/IdGenerator.ts
  tsconfig.json
Labels: Push Inicial

#6 Endpoint getfriendspost - feed
  src/controller/getFriendFeed.ts
  src/data/BaseDatabase.ts
  src/data/UserDatabase.ts
  src/routes/userRouter.ts
  src/services/Authenticator.ts
Labels: enhancement

#7 Implantação do feed por tipo de publicação.
  src/controller/typeFeed.ts
  src/data/PostsDatabase.ts
Labels: enhancement

#5 Unfollow User Finalizado e testes realizados
  src/business/FriendshipBusiness.ts
  src/business/PostsBusiness.ts
  src/controller/removeFriendship.ts
  src/data/UsersRelationsDatabase.ts
  src/routes/postRouter.ts
  src/routes/userRouter.ts
  src/services/Authenticator.ts
Labels: bug, enhancement

#8 Incremento e acertos typefeed
  src/routes/postRouter.ts
Labels: enhancement
